//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AplicacaoAcademia
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class academiaEntities : DbContext
    {
        public academiaEntities()
            : base("name=academiaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ALUNOS> ALUNOS { get; set; }
        public virtual DbSet<SERIES> SERIES { get; set; }
        public virtual DbSet<USUARIO> USUARIO { get; set; }
    }
}
