//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AplicacaoAcademia
{
    using System;
    using System.Collections.Generic;
    
    public partial class SERIES
    {
        public int ID { get; set; }
        public int IDAluno { get; set; }
        public string Segunda_Feira { get; set; }
        public string Terça_Feira { get; set; }
        public string Quarta_Feira { get; set; }
        public string Quinta_Feira { get; set; }
        public string Sexta_Feira { get; set; }
    
        public virtual SERIES SERIES1 { get; set; }
        public virtual SERIES SERIES2 { get; set; }
    }
}
